### PR TITLE
fix: exit 1 when logging error messages

### LINKED ISSUE #603: Username and email inputs not throwing error
Although the error gets reported in the log

image

The action is not failing... I'd recommend throwing out an error. Assigning to @klmcadams. This is a bug.

### PR DESCRIPTION
**Pull request by klmcadams**
Add check to see if bot user or email inputs are empty. If so, log an error message & exit 1. Exiting 1 when logging an error message was applied to the _logging action.

[Exit 1 on error](https://github.com/ansys-internal/actions-sandbox/actions/runs/11278326057/job/31366557792)
[Bot secrets exist, so no error](https://github.com/ansys-internal/actions-sandbox/actions/runs/11278177040/job/31366367645)

Closes #603

### CODE REVIEW

**Review by germa89 — APPROVED** [review]
I think doing `exit 1` when we are loggin an error makes sense... however have you checked that you are not logging anywhere else with ``ERROR`` level? 
Alternatively, you could do that exit optionally using another argument (``force_exit`` maybe?)

Other than that, it looks good to me.

**Comment by klmcadams** [comment]
It looks like the other locations logging with ERROR are [_doc-build-windows](https://github.com/ansys/actions/blob/9e5cc68dd3d411d8318ccc51baae1468cab8d964/_doc-build-windows/action.yml#L368) and [_doc-build-linux](https://github.com/ansys/actions/blob/9e5cc68dd3d411d8318ccc51baae1468cab8d964/_doc-build-linux/action.yml#L362) when it's unable to determine the PDF filename using the conf.py file. If being unable to determine the PDF filename isn't a dealbreaker & the action can still pass without it, I think the logging level for those cases should change to WARNING instead

**Review by SMoraisAnsys — APPROVED** [review]
LGTM For the `doc-build` actions I think it's great to have this early exit because if the error logs are triggered, it means that the job using the action will fail fore sure.

**Comment by SMoraisAnsys** [comment]
> It looks like the other locations logging with ERROR are [_doc-build-windows](https://github.com/ansys/actions/blob/9e5cc68dd3d411d8318ccc51baae1468cab8d964/_doc-build-windows/action.yml#L368) and [_doc-build-linux](https://github.com/ansys/actions/blob/9e5cc68dd3d411d8318ccc51baae1468cab8d964/_doc-build-linux/action.yml#L362) when it's unable to determine the PDF filename using the conf.py file. If being unable to determine the PDF filename isn't a dealbreaker & the action can still pass without it, I think the logging level for those cases should change to WARNING instead

It would break further steps in the action if one triggers any of the error log.

**Review by RobPasMue — APPROVED** [review]
LGTM!

**Comment by RobPasMue** [comment]
Releasing this change

**Pull request merged**
