### PR TITLE
fix: install wget on Windows

### PR DESCRIPTION
**Pull request by RobPasMue**
Solves issues with check-licenses running on Windows

### CODE REVIEW

**Review by germa89 — APPROVED** [review]
Look good to me. Thank you @RobPasMue !!

**Comment by raph-luc** [comment]
I believe `bc` is also missing: https://github.com/ansys/actions/issues/309

**Comment by raph-luc** [comment]
> > I believe `bc` is also missing: #309
> 
> Can't seem to find the line where it says `bc` is missing... Can you point me to it?

Search for `bc: command not found`, it should immediately take you to it:
image

image

**Comment by RobPasMue** [comment]
We'll open a follow-up PR for this. Thanks @raph-luc! Let's keep track of it on #309

**Pull request merged**
