### PR TITLE
fix: ignoring `jinja2` vulnerability ID

### PR DESCRIPTION
**Pull request by clatapie**
`jinja2` is a required dependency for the `check-vulnerability.py` scripts.
Due to `jinja2` [safety result](https://data.safetycli.com/p/pypi/jinja2/97c/), the `check-vulnerabilities` action is failing.

### CODE REVIEW

**Review by jorgepiloto — APPROVED** [review]
It would be great if we could add links or comments at some point for each number.

**Comment by SMoraisAnsys** [comment]
@jorgepiloto Yeah, I do agree (that would also help to know when new releases patch the issues)
For the one added : https://data.safetycli.com/v/70612/97c/ and it affects versions >= 0
image

**Comment by clatapie** [comment]
@jorgepiloto, as it's a `.txt` file, it should not be a problem indeed

**Comment by RobPasMue** [comment]
Links are available in the rendered docs: https://actions.docs.ansys.com/version/dev/vulnerability-actions/index.html
Search for "Accepted safety vulnerabilities"

Comments would be fine too for explaining why we are ignoring it

**Pull request merged**
