### PR TITLE
refactor: use vale-action with branch reviewdog20 to leverage fail_level

### PR DESCRIPTION
**Pull request by SMoraisAnsys**
The PR changes consist in leveraging the newly available branch `reviewdog20` in `vale-action`. The great thing with that branch is that it allows one to specify failing on `warning` instead of `error` to avoid ticking bombs. Moreover, it also bumps the default version of reviewdog to 0.20.2 instead of the default 0.17.0.

> Note: this could already be performed (see https://github.com/ansys/pyaedt/pull/4881) but it required to override the severity level of each warning rule to error. That approach is too manual and prone to miss new changes to be a great solution in the long run.

Old purpose:

~While asking for an update in `vale-action`, I discovered that `level` is no longer an input of this action, see https://github.com/errata-ai/vale-action/commit/c4213d4de3d5f718b8497bd86161531c78992084.~

~I've opened an issue to update the version of `reviewdog` in `vale-action`. If this occurs, `vale-action` could leverage the new feature `fail-level` which could lead to `level` being added back. However, this is just an issue and I don't know what the maintainer will decide, see https://github.com/errata-ai/vale-action/issues/131 for more information.~

~In the mean time, I propose we remove this misleading input which gave me the impression that we could chose the level on which the action will fail.~

### CODE REVIEW

**Comment by RobPasMue** [comment]
Can't we wait to see what the vale maintainer decides? I wouldn't want to duplicate efforts on this.

**Comment by jorgepiloto** [comment]
> Can't we wait to see what the vale maintainer decides? I wouldn't want to duplicate efforts on this.

Agreed. Let's leave this in draft for the moment until Vale and Reviewdog take a final decission.

Thanks for noticing this unused input parameter, Sebastien.

**Comment by SMoraisAnsys** [comment]
> > Can't we wait to see what the vale maintainer decides? I wouldn't want to duplicate efforts on this.
> 
> Agreed. Let's leave this in draft for the moment until Vale and Reviewdog take a final decission.
> 
> Thanks for noticing this unused input parameter, Sebastien.

I'll work on `vale-action` to add this feature. The maintainer doesn't seem to be opposed to adding a `fail-level` !

**Comment by RobPasMue** [comment]
What's the status here @SMoraisAnsys?

**Comment by SMoraisAnsys** [comment]
> What's the status here @SMoraisAnsys?

I didn't have time to work on the vale action and probably won't be able to work on it next week either. If you want to handle the vale action modification, please do so.

**Comment by SMoraisAnsys** [comment]
JSYK, there is a code error in the PR that got merged into `reviewdog20`. I proposed a fix and it seems to be working on the repo. I'll update the PR afterward.
@jorgepiloto You mentioned before that you would like to try the resulting branch to see if it could run on cases where the `reviewdog` branch was failing due to too many changes. Feel free to give a shot at the fix on my fork if you want :)

**Review by MaxJPRey — APPROVED** [review]

**Pull request merged**
